export const LOAD_CATEGORIES = 'FEED/LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'FEED/LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_ERROR = 'FEED/LOAD_CATEGORIES_ERROR';
export const CANCELED_LOAD_CATEGORIES = 'FEED/CANCELED_LOAD_CATEGORIES';
